[project]
name = "morse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pycairo>=1.28.0",
    "pygame>=2.6.1",
    "pygobject>=3.52.3",
]
